# Generated by Django 5.1.1 on 2024-12-10 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img',
            field=models.ImageField(blank=True, default='img1.png', upload_to=''),
        ),
    ]
